[phases.setup]
nixPkgs = ['nodejs', 'php82', 'php82Packages.composer']

[phases.build]
cmds = [
  'echo "🔧 Usando Dockerfile personalizado..."',
  'echo "✅ Build será feito pelo Docker"'
]

[start]
cmd = './docker-start.sh'

[variables]
PORT = '8000'
APP_ENV = 'production'
APP_DEBUG = 'true'
SESSION_DRIVER = 'database'
CACHE_DRIVER = 'database'
QUEUE_CONNECTION = 'database'
LOG_CHANNEL = 'stderr'
LOG_LEVEL = 'debug'
NODE_ENV = 'production'
VITE_APP_NAME = 'Password Manager'
ASSET_URL = ''