[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"

[variables]
APP_ENV = "production"
APP_DEBUG = "true"
SESSION_DRIVER = "database"
CACHE_DRIVER = "database"
QUEUE_CONNECTION = "database"
RUN_MIGRATIONS = "true"