[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"

[variables]
APP_ENV = "production"
APP_DEBUG = "true"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "debug"
SESSION_DRIVER = "database"
CACHE_DRIVER = "database"
QUEUE_CONNECTION = "database"
RUN_MIGRATIONS = "true"
DB_CONNECTION = "mysql"
DB_HOST = "${{MYSQL_HOST}}"
DB_PORT = "${{MYSQL_PORT}}"
DB_DATABASE = "${{MYSQL_DATABASE}}"
DB_USERNAME = "${{MYSQL_USER}}"
DB_PASSWORD = "${{MYSQL_PASSWORD}}"