services:
  - type: web
    name: password-manager
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: "Password Manager"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: errorlog
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: password-manager-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: password-manager-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: password-manager-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: password-manager-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: password-manager-db
          property: password
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120

databases:
  - name: password-manager-db
    databaseName: password_manager
    user: password_manager_user