services:
  - type: web
    name: password-manager
    env: php
    buildCommand: npm install && npm run build && composer install --no-dev --optimize-autoloader
    startCommand: php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql

databases:
  - name: passwordmanager-db
    databaseName: passwordmanager
    user: passwordmanager_user
    plan: free
    region: virginia