name: password-manager
services:
- name: web
  source_dir: /
  github:
    repo: seu-usuario/PasswordManager
    branch: main
  build_command: ./build.sh
  run_command: ./start.do.sh
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /health
  envs:
  - key: APP_NAME
    value: "Password Manager"
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: APP_URL
    value: ${APP_URL}
  - key: LOG_CHANNEL
    value: errorlog
  - key: DB_CONNECTION
    value: mysql
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_PORT
    value: ${db.PORT}
  - key: DB_DATABASE
    value: ${db.DATABASE}
  - key: DB_USERNAME
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
  - key: BROADCAST_DRIVER
    value: log
  - key: CACHE_DRIVER
    value: file
  - key: FILESYSTEM_DISK
    value: local
  - key: QUEUE_CONNECTION
    value: sync
  - key: SESSION_DRIVER
    value: file
  - key: SESSION_LIFETIME
    value: "120"

databases:
- name: db
  engine: MYSQL
  version: "8"
  size: basic
  num_nodes: 1